---
- name: Set index.php as the default page
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DirectoryIndex index.html'
    replace: '#DirectoryIndex index.html \nDirectoryIndex index.php'
  tags: changed to php file

- name: Start Apache service
  service: 
    name: httpd
    enabled: true
    state: started
  tags: started apache

- name: Copy the code from repository
  git:
    repo: '{{ repository }}'
    dest: /var/www/html/
    force: true
  tags: copy repo
